src/welp/config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'sign_in' => 'authentication#sign_in'
  post 'sign_in' => 'authentication#login'
  get 'signed_out' => 'authentication#signed_out'
  get 'new_user' => 'authentication#new_user'
  post 'new_user' => 'authentication#register'
  get 'account_settings' => 'authentication#account_settings'
  put 'account_settings' => 'authentication#set_account_info'
  get 'places/:id' => 'home#show_place', as: :place
  post 'places/:id' => 'home#add_tag'
  delete 'places/delete/:id' => 'home#delete', as: :place_delete
  get 'places/comment/:id' => 'home#new_comment', as: :place_comments
  post 'places/comment/:id' => 'home#add_comment'
  get 'places/add/new' => 'home#new_place', as: :new_place
  post 'places/add/new' => 'home#add_place'
  get 'places/edit/:id' => 'home#edit_place', as: :place_edit
  put 'places/edit/:id' => 'home#change_place'
  get 'users/:id' => 'users#get', as: :user_getter
  get 'users' => 'users#fetcher', as: :user

end

src/welp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="container">

<p>
<% if current_user %>
  Logged in as <%= current_user['username'] %>.
  <%= link_to "Sign Out", signed_out_path %>
  <%= link_to "Account Settings", account_settings_path %>
<% else %>
  Hello, stranger.
  <%= link_to "Sign Up", new_user_path %>
  <%= link_to "Sign In", sign_in_path %>
<% end %>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>