src/welp/config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'sign_in' => 'authentication#sign_in'
  post 'sign_in' => 'authentication#login'
  get 'signed_out' => 'authentication#signed_out'
  get 'new_user' => 'authentication#new_user'
  post 'new_user' => 'authentication#register'
  get 'account_settings' => 'authentication#account_settings'
  put 'account_settings' => 'authentication#set_account_info'
  get 'places/:id' => 'home#show_place', as: :place
  post 'places/:id' => 'home#add_tag'
  delete 'places/delete/:id' => 'home#delete', as: :place_delete
  get 'places/comment/:id' => 'home#new_comment', as: :place_comments
  post 'places/comment/:id' => 'home#add_comment'
  get 'places/add/new' => 'home#new_place', as: :new_place
  post 'places/add/new' => 'home#add_place'
  get 'places/edit/:id' => 'home#edit_place', as: :place_edit
  put 'places/edit/:id' => 'home#change_place'
  get 'users/:id' => 'users#get', as: :user_getter
  get 'users' => 'users#fetcher', as: :user

end

src/welp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:places].nil?
      sql_select_places = 'SELECT place_id, name, street, num, zip, city, phone, website FROM places;'
    else
      sql_select_places = "SELECT place_id, name, street, num, zip, city, phone, website FROM places where lower(name) LIKE '%#{params[:places]}%' OR lower(city) LIKE '%#{params[:places]}%' ORDER BY name = '#{params[:places]} DESC', name ASC, city ASC"
    end
    @places = ActiveRecord::Base.connection.execute(sql_select_places)
  end

  def show_place
    sql_fetch_place = "SELECT * FROM places WHERE place_id = #{params[:id]};"
    @place_info = ActiveRecord::Base.connection.execute(sql_fetch_place).first
    sql_fetch_type = "SELECT * FROM #{@place_info['kind']}s WHERE place_id = #{params[:id]}"
    @type_info = ActiveRecord::Base.connection.execute(sql_fetch_type).first

    sql_fetch_alltags = 'SELECT DISTINCT name FROM tags ORDER BY name ASC;'
    @all_tags = ActiveRecord::Base.connection.execute(sql_fetch_alltags).sort_by { |t| t['name'] }.map(&:to_a).map(&:last)

    sql_fetch_placetags = "SELECT name, count(name) FROM tags WHERE place_id = #{params[:id]} GROUP BY name ORDER BY count DESC;"
    @place_tags = ActiveRecord::Base.connection.execute(sql_fetch_placetags).map { |tag| "#{tag['name']} (#{tag['count']})" }.join(', ')

    sql_fetch_comments = "SELECT c.text_comment, c.stars, c.creation_date, u.username, u.user_id FROM comments c INNER JOIN users u ON c.user_id = u.user_id WHERE place_id = #{params[:id]} ORDER BY c.creation_date DESC;"
    @place_comments = ActiveRecord::Base.connection.execute(sql_fetch_comments)

    @mean_note = begin
                   @place_comments.inject(0) { |acc, comment| acc += comment['stars'].to_f } / @place_comments.count
                 rescue
                   0
                 end
  end

  def add_tag
    newtag = params[:addtagmanual].nil? ? params[:addtag] : params[:addtagmanual]
    sql_fetch_tag = "SELECT * FROM tags WHERE place_id = #{params[:id]} AND user_id = #{current_user['user_id']} AND name = '#{newtag}'"
    if ActiveRecord::Base.connection.execute(sql_fetch_tag).count != 0
      flash.now[:error] = 'You have already flagged this tag'
    else
      sql_add_tag = "INSERT INTO tags(place_id, user_id, name) VALUES (#{params[:id]}, #{current_user['user_id']}, '#{newtag}');"
      ActiveRecord::Base.connection.execute(sql_add_tag)
    end
    redirect_to action: 'show_place'
  end

  def new_comment
  end

  def add_comment
    sql_fetch_comment_date = "SELECT creation_date FROM comments WHERE place_id = #{params[:id]} AND user_id = #{current_user['user_id']};"
    last_comment = ActiveRecord::Base.connection.execute(sql_fetch_comment_date)
    if last_comment.max { |c| c['creation_date'] } == DateTime.now.to_date.to_s
      flash.now[:error] = 'You have already commented this place today'
    else
      sql_add_comment = "INSERT INTO comments(place_id, user_id, stars, text_comment, creation_date) VALUES (#{params[:id]}, #{current_user['user_id']}, #{params[:stars]}, '#{params[:comment].gsub("'", "''")}', '#{DateTime.now.to_date}')"
      ActiveRecord::Base.connection.execute(sql_add_comment)
    end
    redirect_to action: 'show_place'
  end

  def edit_place
    sql_fetch_place = "SELECT * FROM places WHERE place_id = #{params[:id]};"
    @place_info = ActiveRecord::Base.connection.execute(sql_fetch_place).first
    sql_fetch_type = "SELECT * FROM #{@place_info['kind']}s WHERE place_id = #{params[:id]}"
    @type_info = ActiveRecord::Base.connection.execute(sql_fetch_type).first
    @days = ['Monday AM', 'Monday PM', 'Tuesday AM', 'Tuesday PM', 'Wednesday AM', 'Wednesday PM', 'Thursday AM', 'Thursday PM', 'Friday AM', 'Friday PM', 'Saturday AM', 'Saturday PM', 'Sunday AM', 'Sunday PM']
  end

  def change_place
    sql_update_place = "UPDATE places SET name = '#{params[:name]}', street = '#{params[:street]}', num = #{params[:num]}, zip = '#{params[:zip]}', city = '#{params[:city]}', phone = '#{params[:phone]}', website = '#{params[:website]}' WHERE place_id = #{params[:id]} returning kind"
    kind = ActiveRecord::Base.connection.execute(sql_update_place).first['kind']
    case kind
    when 'restaurant'
      sql_update_restaurant = "UPDATE restaurants SET price_range = #{params[:price_range]}, banquet = #{params[:banquet]}, take_out = '#{params[:take_out] == 't'}', delivery = '#{params[:delivery] == 't'}' WHERE place_id = #{params[:id]};"
      ActiveRecord::Base.connection.execute(sql_update_restaurant)
    when 'cafe'
      sql_update_cafe = "UPDATE cafes SET smoking = '#{params[:smoking] == 't'}', snack = '#{params[:snack] == 't'}' WHERE place_id = #{params[:id]};"
      ActiveRecord::Base.connection.execute(sql_update_cafe)
    else
      sql_update_hotel = "UPDATE hotels SET num_stars = #{params[:num_stars]}, num_rooms = #{params[:num_rooms]}, price_range_double_room = #{params[:price_range_double_room]} WHERE place_id = #{params[:place_id]};"
      ActiveRecord::Base.connection.execute(sql_update_hotel)
    end
    redirect_to action: 'show_place'
  end

  def new_place
  end

  def add_place
    sql_add_place = "INSERT INTO places(creator_id, creation_date, name, street, num, zip, city, phone, website, kind) VALUES (#{current_user['user_id']}, '#{DateTime.now.to_date}', '#{params[:name]}', '#{params[:street]}', #{params[:num]}, '#{params[:zip]}', '#{params[:city]}', '#{params[:phone]}', '#{params[:website]}', '#{params[:kind]}') returning place_id;"
    place_id = ActiveRecord::Base.connection.execute(sql_add_place).first['place_id']
    sql_add_type = case params[:kind]
                   when 'cafe'
                     "INSERT INTO cafes(place_id, smoking, snack) VALUES (#{place_id}, '#{params[:smoking] == 't'}', '#{params[:snack] == 't'}');"
                   when 'hotel'
                     "INSERT INTO hotels(place_id, num_stars, num_rooms, price_range_double_room) VALUES (#{place_id}, #{params[:num_stars]}, #{params[:num_rooms]}, #{params[:price_range_double_room]});"
                   when 'restaurant'
                     "INSERT INTO restaurants(place_id, price_range, banquet, take_out, delivery, closed) VALUES (#{place_id}, #{params[:price_range]}, #{params[:banquet]}, '#{params[:take_out] == 't'}', '#{params[:delivery] == 't'}', 'B00000000000000');"
    end
    ActiveRecord::Base.connection.execute(sql_add_type)
    redirect_to :root
  end

  def delete
    sql_delete_place = "DELETE FROM places WHERE place_id = #{params[:id]};"
    ActiveRecord::Base.connection.execute(sql_delete_place)
    redirect_to :root
  end
end

src/welp/app/helpers/home_helper.rb
module HomeHelper
end

src/welp/app/views/home/edit_place.html.erb
<h1>Edit <%= @place_info['name'] %></h1>

<%= form_tag({controller: 'home', action: 'change_place'}, {method: 'put'}) do %>
  <div class="form-group">
    <%=label_tag(:name, "Place Name:") %>
    <%=text_field_tag :name, @place_info['name'], class: "form-control" %>
  </div>
  <div class="form-group">
    <%=label_tag(:street, "Street:") %>
    <%=text_field_tag :street, @place_info['street'], class: "form-control" %>
  </div>
  <div class="form-group">
    <%=label_tag(:num, "Number:") %>
    <%= number_field_tag :num, @place_info['num'], min: 0, step: 1, class: "form-control" %>
  </div>
  <div class="form-group">
    <%=label_tag(:zip, "Zip code:") %>
    <%=text_field_tag :zip, @place_info['zip'], class: "form-control" %>
  </div>
  <div class="form-group">
    <%=label_tag(:city, "City:") %>
    <%=text_field_tag :city, @place_info['city'], class: "form-control" %>
  </div>
  <div class="form-group">
    <%=label_tag(:phone, "Phone:") %>
    <%=text_field_tag :phone, @place_info['phone'], class: "form-control" %>
  </div>
  <div class="form-group">
    <%=label_tag(:website, "Phone:") %>
    <%=text_field_tag :website, @place_info['website'], class: "form-control" %>
  </div>
  <% if @place_info['kind'] == 'cafe' %>
    <div class="form-group">
      <%=label_tag(:smoking, "Smoking:") %>
      <%= check_box_tag :smoking, 't', @type_info['smoking'] == 't', class: "checkbox" %>
    </div>
    <div class="form-group">
      <%=label_tag(:snack, "Snack:") %>
      <%= check_box_tag :snack, 't', @type_info['snack'] == 't', class: "checkbox" %>
    </div>
  <% elsif @place_info['kind'] == 'restaurant' %>
    <div class="form-group">
      <%=label_tag(:price_range, "Price range:") %>
      <%=number_field_tag :price_range, @type_info['price_range'], class: "form-control" %>
    </div>
    <div class="form-group">
      <%=label_tag(:banquet, "Places for banquet:") %>
      <%=number_field_tag :banquet, @type_info['banquet'], class: "form-control" %>
    </div>
    <div class="form-group">
      <%=label_tag(:take_out, "Take Away:") %>
      <%= check_box_tag :take_out, 't', @type_info['take_out'] == 't', class: "checkbox" %>
    </div>
    <div class="form-group">
      <%=label_tag(:delivery, "Delivery:") %>
      <%= check_box_tag :delivery, 't', @type_info['delivery'], class: "checkbox" %>
    </div>
  <% else %>
    <div class="form-group">
      <%=label_tag(:num_stars, "Stars:") %>
      <%=number_field_tag :num_stars, @type_info['num_stars'], min:0, max: 5, step:1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%=label_tag(:num_rooms, "Rooms:") %>
      <%=number_field_tag :num_rooms, @type_info['num_rooms'], min:0, step:1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%=label_tag(:price_range_double_room, "Double room price:") %>
      <%=number_field_tag :price_range_double_room, @type_info['price_range_double_room'], min:0, step:1, class: "form-control" %>
    </div>
  <% end %>
  <div class="form-group">
    <%= submit_tag 'Update', class: "btn btn-primary btn-lg" %>&nbsp;&nbsp;&nbsp;
    <%= submit_tag 'Clear Form', :type => 'reset', class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

src/welp/app/views/home/index.html.erb
<h1>WELP search engine</h1>
<%= link_to 'Looking for a user ?', user_path %>

<section class="search-form">
  <%= form_tag({controller: 'home', action: 'index', url: 'root'}, method: 'get') do %>
    <div class="input-group input-group-lg">
      <%= label_tag :places, nil, class: "sr-only" %>
      <%= text_field_tag :places, nil,
              placeholder: "Search for places...",
              class: "form-control input-lg" %>
      <span class="input-group-btn">
        <%= submit_tag "Find places", class: "btn btn-primary btn-lg" %>
      </span>
    </div>
  <% end %>
</section>

<section class="search-results">
  <h2>Results</h2>
  <% if current_user && current_user['is_admin'] == 't' %>
    <%= link_to "Add a new place", new_place_path %>
  <% end %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Street</th>
        <th>Number</th>
        <th>City</th>
        <th>Phone</th>
      </tr>
    </thead>
    <tbody>
      <% @places.each do |place| %>
        <tr>
          <td>
            <% if place['website'] != 'NULL' %>
                  <%= link_to place['name'], place['website'] %>
            <% else %>
                  <%= place['name'] %>
            <% end %>
          </td>
          <td><%= place['street'] %></td>
          <td><%= place['num'] %></td>
          <td><%= place['city'] %></td>
          <td><%= place['phone'] %></td>
          <td><%= link_to "more", place_path(place['place_id']) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

src/welp/app/views/home/new_comment.html.erb
<h1>New comment</h1>

<%= form_tag({controller: 'home', action: 'add_comment'}, method: 'post') do %>
<div class="form-group">
  <%= label_tag(:stars, "NOTE (out of 5):") %>
  <%= number_field_tag :stars, 5, min: 0, max: 5, step: 1 %>
</div>
  <div class="form-group">
    <%=label_tag(:comment, "New comment:") %>
    <%=text_field_tag :comment , nil, class: "form-control"%>
  </div>
  <%= submit_tag 'submit'%>
<% end %>

src/welp/app/views/home/new_place.html.erb
<h1>Create</h1>

<%= form_tag({controller: 'home', action: 'add_place'}, {method: 'post'}) do %>
  <div class="form-group">
    <%=label_tag(:name, "Place Name:") %>
    <%=text_field_tag :name, nil, class: "form-control" %>
  </div>
  <div class="form-group">
    <%=label_tag(:street, "Street:") %>
    <%=text_field_tag :street, nil, class: "form-control" %>
  </div>
  <div class="form-group">
    <%=label_tag(:num, "Number:") %>
    <%= number_field_tag :num, nil, min: 0, step: 1, class: "form-control" %>
  </div>
  <div class="form-group">
    <%=label_tag(:zip, "Zip code:") %>
    <%=text_field_tag :zip, nil, class: "form-control" %>
  </div>
  <div class="form-group">
    <%=label_tag(:city, "City:") %>
    <%=text_field_tag :city, nil, class: "form-control" %>
  </div>
  <div class="form-group">
    <%=label_tag(:phone, "Phone:") %>
    <%=text_field_tag :phone, nil, class: "form-control" %>
  </div>
  <div class="form-group">
    <%=label_tag(:website, "Phone:") %>
    <%=text_field_tag :website, nil, class: "form-control" %>
  </div>

  <div class="form-group">
    <%=label_tag(:kind, "Cafe:") %>
    <%= radio_button_tag :kind, 'cafe', class: "radio" %>&nbsp;&nbsp;&nbsp;
    <%=label_tag(:kind, "Hotel:") %>
    <%= radio_button_tag :kind, 'hotel', class: "radio" %>&nbsp;&nbsp;&nbsp;
    <%=label_tag(:kind, "Restaurant:") %>
    <%= radio_button_tag :kind, 'restaurant', class: "radio" %>
  </div>

<h2>Specific options for cafes</h2>
    <div class="form-group">
      <%=label_tag(:smoking, "Smoking:") %>
      <%= check_box_tag :smoking, 't', nil, class: "checkbox" %>
    </div>
    <div class="form-group">
      <%=label_tag(:snack, "Snack:") %>
      <%= check_box_tag :snack, 't', nil, class: "checkbox" %>
    </div>


<h2>Specific options for restaurants</h2>
    <div class="form-group">
      <%=label_tag(:price_range, "Price range:") %>
      <%=number_field_tag :price_range, nil, class: "form-control" %>
    </div>
    <div class="form-group">
      <%=label_tag(:banquet, "Places for banquet:") %>
      <%=number_field_tag :banquet, nil, class: "form-control" %>
    </div>
    <div class="form-group">
      <%=label_tag(:take_out, "Take Away:") %>
      <%= check_box_tag :take_out, 't', nil, class: "checkbox" %>
    </div>
    <div class="form-group">
      <%=label_tag(:delivery, "Delivery:") %>
      <%= check_box_tag :delivery, 't', nil, class: "checkbox" %>
    </div>

<h2>Specific options for hotels</h2>
    <div class="form-group">
      <%=label_tag(:num_stars, "Stars:") %>
      <%=number_field_tag :num_stars, nil, min:0, max: 5, step:1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%=label_tag(:num_rooms, "Rooms:") %>
      <%=number_field_tag :num_rooms, nil, min:0, step:1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%=label_tag(:price_range_double_room, "Double room price:") %>
      <%=number_field_tag :price_range_double_room, nil, min:0, step:1, class: "form-control" %>
    </div>
  <div class="form-group">
    <%= submit_tag 'Update', class: "btn btn-primary btn-lg" %>&nbsp;&nbsp;&nbsp;
    <%= submit_tag 'Clear Form', :type => 'reset', class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

src/welp/app/views/home/show_place.html.erb
<h1><%= @place_info['name'] %></h1>

<section>
  <h2>Informations</h2>
  <% if current_user && current_user['is_admin'] == 't' %>
    <%= link_to "Modify", place_edit_path(params[:id]) %>
    <%= link_to "Delete", place_delete_path(params[:id]) , method: :delete%>
  <% end %>
  <p>
    <b>Mean Note</b>: <%= @mean_note.round(2) %>/5
  </p>
  <p>
    <b>Address</b>: <%= @place_info['num'] %> <%= @place_info['street'] %>, <%= @place_info['city'] %>, <%= @place_info['zip'] %>
  </p>
  <p>
    <% if @place_info['phone'] != 'NULL' %>
      <b>Phone number</b>: <%= @place_info['phone'] %>
    <% end %>
  </p>
  <p>
    <% if @place_info['website'] != 'NULL' %>
      <b>Website</b>: <%= link_to @place_info['website'], @place_info['website'] %>
    <% end %>
  </p>
  <p>
    <b>Tags</b>: <%= @place_tags %>
    <% if current_user %>
      <%= form_tag({controller: 'home', action: 'add_tag', url: 'add_tag'}, method: 'post') do %>
        <%= select_tag :addtag, options_from_collection_for_select(@all_tags, :last, :last ) %>
        or add a new tag
        <%=text_field_tag :addtagmanual %>
        <%= submit_tag 'add'%>
      <% end %>
    <% end %>
  </p>

  <% if @place_info['kind'] == 'restaurant' %>
    <p>
      <b>Price range</b>: <%= @type_info['price_range'] %> eur.
    </p>
    <p>
      <b>Places for banquet</b>: <%= @type_info['banquet'] %>
    </p>
    <p>
      <% if @type_info['take_out'] == 't' %>
        Possibility to take away
      <% end %>
    </p>
    <p>
      <% if @type_info['delivery'] == 't' %>
        <b>Delivery</b>: yes
      <% end %>
    </p>
    <p>
      <b>Openings</b>:
    </p>
    <p>
      <table>
        <thead>
          <tr>
            <th>Monday AM</th>
            <th>Monday PM</th>
            <th>Tuesday AM</th>
            <th>Tuesday PM</th>
            <th>Wednesday AM</th>
            <th>Wednesday PM</th>
            <th>Thursday AM</th>
            <th>Thursday PM</th>
            <th>Friday AM</th>
            <th>Friday PM</th>
            <th>Saturday AM</th>
            <th>Saturday PM</th>
            <th>Sunday AM</th>
            <th>Sunday PM</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @type_info['closed'].chars.each do |c| %>
              <% if c == '1' %>
                <td>X</td>
              <% else %>
                <td>O</td>
              <% end %>
            <% end %>
          </tr>
        </tbody>
      </table>
    </p>
  <% elsif @place_info['kind'] == 'cafe' %>
    <p>
      <% if @type_info['snack'] == 't' %>
        <b>Snack</b>
      <% end %>
    </p>
    <p>
      <% if @type_info['smoking'] == 't' %>
        <b>Smoking authorized</b>
      <% end %>
    </p>
  <% else %>
    <p>
      <b><%= @type_info['num_stars'] %> stars</b>
    </p>
    <p>
      <b><%= @type_info['num_rooms'] %> rooms</b>
    </p>
    <p>
      <b>Double room price</b>: <%= @type_info['price_range_double_room'] %>
    </p>
  <% end %>
</section>

<section>
<h2>Comments</h2>
  <% if current_user %>
    <%= link_to "New comment", place_comments_path(params[:id]) %>
  <% end %>

  <ol class="list-group">
    <% @place_comments.each do |comment| %>
      <li class="list-group-item clearfix">
        <h3 class="pull-right">
          <small class="text_uppercase">Created</small>
          <%= comment['creation_date'].to_date %>
        </h3>
        <h3>
          <%= link_to comment['username'], user_getter_path(comment['user_id']) %>
          <small><%= comment['stars'] %>/5</small>
        </h3>
        <h4><%= comment['text_comment'] %></h4>
      </li>
    <% end %>
  </ol>
</section>